---
language: cpp
os:
  - linux
  - osx
compiler: 
  - clang
  - gcc
before_install:
  - if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -q; fi
  - if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install g++-4.8 -y; fi
  - if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX="g++-4.8"; fi
  - if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then g++-4.8 -v; fi
  - g++ -v;

# Change this to your needs
script:  make && make clean